---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(stringr)
library(readxl)
```

```{r}
hierachy <- fread("../data/kzis-hierarchy-2023.tsv", colClasses = "character", sep = "\t")
```

```{r}
klucz <- read_excel("../data-raw/ksiz_kody_2014_2022_klucz.xls", 
                    col_names = c("zawod_old", "nazwa_old", "zawod_new", "nazwa_new"), skip = 1, col_types = "text")
klucz <- setDT(klucz)
klucz <- klucz[zawod_old != zawod_new]
```

```{r}
cbop1 <- fread("../data/cbop-train-2020-2022-no-employer.tar.gz", colClasses = "character")
cbop2 <- fread("../data/cbop-train-2022-2023-no-employer.tar.gz", colClasses = "character")
cbop <- rbind(cbop1,cbop2) |> unique()
cbop <- cbop[code != "000000"]
cbop[klucz[, .(code = zawod_old, code_new = zawod_new)], on = "code", code_new:=i.code_new]
cbop[!is.na(code_new), code := code_new]
cbop[,code_new := NULL]
cbop[, desc_nchars := nchar(desc)]
cbop$desc_nchars |> summary()

cbop[, desc_nchars_cit := cut(desc_nchars, c(0, 50, 100, 200, 300, 400, 500, Inf),
                              include.lowest = T,
                              right = T)]

cbop[,.N, keyby=desc_nchars_cit]
head(cbop)
```

Distribution is very skewed so we will sample 25 examples or 10% from each 

```{r}
set.seed(2024)
cbop_sample <- cbop[, .SD[sample(.N, min(round(0.2*.N), .N))], .(code, desc_nchars_cit)]
fwrite(x = cbop_sample[, .(code, desc)], file = "../data/cbop-for-train-test.tar.gz", quote = T)
```

Whole dataset

```{r}
fwrite(x = cbop[1:200000, .(code, desc)], file = "../data/cbop-for-train-test-whole-1.tar.gz", quote = T)
fwrite(x = cbop[200001:400000, .(code, desc)], file = "../data/cbop-for-train-test-whole-2.tar.gz", quote = T)
fwrite(x = cbop[400001:600000, .(code, desc)], file = "../data/cbop-for-train-test-whole-3.tar.gz", quote = T)
fwrite(x = cbop[600000:823297, .(code, desc)], file = "../data/cbop-for-train-test-whole-4.tar.gz", quote = T)
```

```{r}
fwrite(cbop[, .N, code], "../data-raw/cbop-codes-2024.csv")
```

