---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(sampling)
library(stringr)
```

Official hierarchy

```{r}
hierachy <- fread("../data/kzis-hierarchy-2023.tsv", colClasses = "character", sep = "\t")
```

For training only

```{r}
official <- fread("../data/kzis-occup-dictionary-long-2024.csv", colClasses = "character")
official[nchar(code) == 5, code:=paste0("0", code)]
thes <- fread("../data/gus-thesaurus.csv", colClasses = "character")
```

For testing only

```{r}
hand_1k <- fread("../data/hand-coded-1k.csv", colClasses = "character")
```

For both

```{r}
info <- fread("../data/kzis-occup-infodoradca-2024-updated.csv", colClasses = "character")
kprm <- fread("../data/kprm-selected.csv", colClasses = "character")
hand <- fread("../data/hand-coded.csv", colClasses = "character")
esco <- fread("../data/esco-kzis-selected.csv", colClasses = "character")
cbop <- fread("../data/cbop-for-train-test.tar.gz", colClasses = "character")
```

## Sampling by class

Create training and test data wit 20% of CBOP data

```{r}
set.seed(123)

all_sources <- rbind(info[, source:="info"], 
                     kprm[, source:="kprm"][, .(class=code, desc, source)], 
                     hand[, source:="hand"][, .(class=code, desc, source)], 
                     esco[, source:="esco"][, .(class=code, desc, source)], 
                     cbop[, source:="cbop"][, .(class=code, desc, source)])

all_sources[, size := .N, class]
all_sources[, size_test := round(size*0.7), class]
all_sources[, id:=1:.N]

train_data <- all_sources[, .SD[sample(.N, size_test[1])], class]
test_data <- all_sources[!id %in% train_data$id]

test_data <- rbind(test_data, all_sources[size == 1])

train_data <- rbind(train_data, official[, source:="official"], thes[, source:="gus"], fill = T)
test_data <- rbind(test_data, hand_1k[, source:="hand1k"], fill = T)
```

```{r}
fwrite(x = test_data[, .(class, desc=desc, source)], file = "../data/train-test/test-data-2024.tar.gz")
fwrite(x = train_data[, .(class, desc=desc, source)], file = "../data/train-test/train-data-2024.tar.gz")
```


Create training and test data wit whole CBOP data

```{r}
cbop1 <- fread("../data/cbop-for-train-test-whole-1.tar.gz", colClasses = "character")
cbop2 <- fread("../data/cbop-for-train-test-whole-2.tar.gz", colClasses = "character")
cbop3 <- fread("../data/cbop-for-train-test-whole-3.tar.gz", colClasses = "character")
cbop4 <- fread("../data/cbop-for-train-test-whole-4.tar.gz", colClasses = "character")
```

```{r}
set.seed(123)

all_sources <- rbind(info[, source:="info"], 
                     kprm[, source:="kprm"][, .(class=code, desc, source)], 
                     hand[, source:="hand"][, .(class=code, desc, source)], 
                     esco[, source:="esco"][, .(class=code, desc, source)], 
                     cbop1[, source:="cbop"][, .(class=code, desc, source)],
                     cbop2[, source:="cbop"][, .(class=code, desc, source)],
                     cbop3[, source:="cbop"][, .(class=code, desc, source)],
                     cbop4[, source:="cbop"][, .(class=code, desc, source)])

all_sources[, size := .N, class]
all_sources[, size_test := round(size*0.7), class]
all_sources[, id:=1:.N]

train_data <- all_sources[, .SD[sample(.N, size_test[1])], class]
test_data <- all_sources[!id %in% train_data$id]

test_data <- rbind(test_data, all_sources[size == 1])

train_data <- rbind(train_data, official[, source:="official"], thes[, source:="gus"], fill = T)
test_data <- rbind(test_data, hand_1k[, source:="hand1k"], fill = T)
```

```{r}
fwrite(x = test_data[, .(class, desc=desc, source)], file = "../data/train-test/test-data-whole-2024.tar.gz")
fwrite(x = train_data[, .(class, desc=desc, source)], file = "../data/train-test/train-data-whole-2024.tar.gz")
```

## Simple random sample

Limited CBOP data

```{r}
set.seed(123)
all_sources <- rbind(info[, source:="info"], 
                     kprm[, source:="kprm"][, .(class=code, desc, source)], 
                     hand[, source:="hand"][, .(class=code, desc, source)], 
                     esco[, source:="esco"][, .(class=code, desc, source)], 
                     cbop[, source:="cbop"][, .(class=code, desc, source)])

all_sources[, id:=1:.N]

train_data <- all_sources[, .SD[sample(1:.N, round(.N*0.70))], source]
test_data <- all_sources[!id %in% train_data$id]

train_data <- rbind(train_data, official[, source:="official"], thes[, source:="gus"], fill = T)
test_data <- rbind(test_data, hand_1k[, source:="hand1k"], fill = T)
```

```{r}
fwrite(x = test_data[, .(class, desc=desc, source)], file = "../data/train-test/test-data-source-2024.tar.gz")
fwrite(x = train_data[, .(class, desc=desc, source)], file = "../data/train-test/train-data-source-2024.tar.gz")
```

Whole CBOP data

```{r}
set.seed(123)

all_sources <- rbind(info[, source:="info"], 
                     kprm[, source:="kprm"][, .(class=code, desc, source)], 
                     hand[, source:="hand"][, .(class=code, desc, source)], 
                     esco[, source:="esco"][, .(class=code, desc, source)], 
                     cbop1[, source:="cbop"][, .(class=code, desc, source)],
                     cbop2[, source:="cbop"][, .(class=code, desc, source)],
                     cbop3[, source:="cbop"][, .(class=code, desc, source)],
                     cbop4[, source:="cbop"][, .(class=code, desc, source)])

all_sources[, id:=1:.N]

train_data <- all_sources[, .SD[sample(1:.N, round(.N*0.70))], source]
test_data <- all_sources[!id %in% train_data$id]

train_data <- rbind(train_data, official[, source:="official"], thes[, source:="gus"], fill = T)
test_data <- rbind(test_data, hand_1k[, source:="hand1k"], fill = T)
```

```{r}
fwrite(x = test_data[, .(class, desc=desc, source)], file = "../data/train-test/test-data-whole-source-2024.tar.gz")
fwrite(x = train_data[, .(class, desc=desc, source)], file = "../data/train-test/train-data-whole-source-2024.tar.gz")
```

